baseURL: 'https://jmiqaweb01.nexsure.com/nexui/'
browser: 'chrome' # 'chrome'|'chromium'|'firefox'|'webkit'
headless: true
parallel: 4 # workers
retries: 0
screenshot: 'on'
video: 'on' # 'on', 'off', 'retain-on-failure', 'on-first-retry'
Artifacts: 'on' # 'on', 'off'
elementHighlight: true
